targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      
      freezed:
        options:
          map: true
          when: true
          maybeMap: true
          maybeWhen: true
          copyWith: true
          equal: true
          toString: true
          
      injectable_generator:
        options:
          auto_register: true
          class_name_pattern: "^_?(.*)$"
          
      auto_route_generator:
        options:
          replace_in_routing_table: true
          
global_options:
  json_serializable:
    options:
      any_map: false
      checked: true
      create_factory: true
      create_to_json: true
      disallow_unrecognized_keys: false
      explicit_to_json: true
      field_rename: none
      generic_argument_factories: false
      ignore_unannotated: false
      include_if_null: true 